### ISSUE TITLE
3 이라는 숫자도 변수화 해주세요 

### ISSUE THREAD

**Issue by niceaji** [khl2bb/start-fe#1]
https://github.com/khl2bb/start-fe/blob/8a5fdc865fff0b45fb2b55b6879ea0d131b0d860/04/quiz1.html#L1003

**Comment by khl2bb** [comment]
넵 방금 강의에서도 변수화를 보고 왔습니다.
 변수화 하겠습니다. 감사합니다.

**Comment by khl2bb** [comment]
29e0f8778c240912876c9488004bae2307190b63
변수화 했습니다
중복되는 코드 줄였습니다.
삼항연산자로 더 줄일 수 있는데 if else가 연산에는 효율적인 것 같아서 놔두었습니다.
상황에 유연하도록 변수를 정하였습니다.
