### ISSUE TITLE
왜 이런식으로 작성했나요?

### ISSUE THREAD

**Issue by niceaji** [khl2bb/start-fe#2]
https://github.com/khl2bb/start-fe/blob/8a5fdc865fff0b45fb2b55b6879ea0d131b0d860/04/quiz1.html#L1003

**Comment by khl2bb** [comment]
html 파일만 업로드 해야되는줄 알고
js, css를 html 안에다 넣었습니다.
다음에는 파일을 분리하겠습니다.

**Comment by khl2bb** [comment]
강의에 나온 것처럼 js파일을 분리하였습니다.
40d11b13547f6453896a2f75b5a585c933f51f15
해당 관련 커밋입니다.
https://github.com/khl2bb/start-fe/commit/40d11b13547f6453896a2f75b5a585c933f51f15
