### ISSUE TITLE
마우스클릭이 잘안이루어질때가 어떤경우였죠?  

### ISSUE THREAD

**Issue by niceaji** [khl2bb/start-fe#3]
https://github.com/khl2bb/start-fe/blob/8a5fdc865fff0b45fb2b55b6879ea0d131b0d860/04/quiz1.html#L1003

이부분 코드는 없어도 될것 같은데요?

**Comment by khl2bb** [comment]
처음에 작업할 때 마우스 클릭이 조금만 드래그 처럼 되버리면
click event target 으로 지정이 안되어서 추가하게 되었습니다.
https://github.com/khl2bb/start-fe/blob/8a5fdc865fff0b45fb2b55b6879ea0d131b0d860/04/quiz2.html#L81
이 경우는
마우스 클릭하려다가 실수로 드래그해도 마우스가 올려져 있는 타일을 빨간색으로 바꾸게
하기 위해 작성했습니다.
사실 클릭을 잘하면 되는 부분이라서 삭제하겠습니다.

**Comment by khl2bb** [comment]
해당 관련 코드(함수)를 주석처리하였습니다. 
정상 작동합니다.
혹시 몰라서 삭제는 안 했습니다. 
8655272f9f0891cc7bb41c86f579fc539e91ddc5
